### ISSUE TITLE
[FEAT]:  text-animations/split-text/Enhanced Contribute Section in TabbedLayout Component 

### ISSUE THREAD

**Issue by aryyan0701** [DavidHDev/react-bits#3]
**Description**
The TabbedLayout component has been enhanced with several UI and UX improvements, particularly focusing on the 'contribute-container' section. These changes aim to provide users with a more interactive and visually appealing experience when contributing to the project.

**Old UI**
![old](https://github.com/user-attachments/assets/21c07d02-8b4d-487a-8684-1066de47f4a1)

**New UI**
![new](https://github.com/user-attachments/assets/b4df4730-b16d-4416-93d1-46f25729cd32)

**Proposal**
I propose the following enhancements to the TabbedLayout component:

- Added Chakra UI's Tooltip to provide additional context to the buttons for reporting bugs and requesting features.
- Introduced badges with color schemes to distinguish between "Bug" and "Feature" actions, making it easier for users to identify the type of contribution.
- Displayed a contribution summary at the bottom of the 'contribute-container' section, showcasing the total number of contributions, giving users a sense of community and impact.

**Acceptance Criteria**
- [ ] Review if the improved UI and UX align with the project's design principles.
- [ ] Confirm whether the additional features (e.g., tooltips, badges, contribution statistics) are beneficial to the user experience.
- [ ] Approve if these enhancements are suitable for a pull request to be merged into the project.

**Comment by DavidHDev** [comment]
Hi @aryyan0701 , I appreciate your time, but your new design looks is definitely not better than the current one. The goal here is to keep a minimal, easy to read interface with a clear purpose. 

Your updates make it very hard to read, the "bug" and "feature" tags do not match the color scheme of the website and their contrast is way off, and the "total contributions" part is totally not needed, I've never seen a project display the number of contributions in their documentation, it's just not useful to anybody. 

I will close this issue because of all these reasons

Thank you!

**Comment by aryyan0701** [comment]
Hello @DavidHDev  

Thank you for your feedback and for reviewing this. I understand the importance of maintaining a minimal and readable interface, and I appreciate your insights on what works best for the project.

I'll keep these principles in mind for future contributions and look forward to finding ways to add value to the project.
